name:                SampleB
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- optparse-simple

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates
- -Wnoncanonical-monad-instances
- -Wredundant-constraints
- -Wtabs

executables:
  SampleB-exe:
    main: app/Main.hs
